// Shared industry options used by the Research Agent and Campaign forms.
// "Other" is always last so users can pick something not listed.
export const INDUSTRIES = [
  "FinTech",
  "Banking",
  "Insurance / InsurTech",
  "SaaS",
  "AI / Machine Learning",
  "Cybersecurity",
  "E-commerce / Retail",
  "Healthcare",
  "HealthTech",
  "Pharmaceuticals",
  "Biotech",
  "Logistics",
  "Supply Chain",
  "Transportation / Mobility",
  "Automotive",
  "Manufacturing",
  "AgriTech",
  "Agriculture",
  "Food & Beverage",
  "CleanTech / Renewable Energy",
  "Energy & Utilities",
  "Mining",
  "EdTech",
  "Real Estate / PropTech",
  "Construction",
  "Hospitality / Travel",
  "Media & Entertainment",
  "Gaming",
  "Marketing & Advertising",
  "Telecom",
  "Professional Services / Consulting",
  "Legal / LegalTech",
  "HR / Recruitment",
  "Aerospace & Defense",
  "Nonprofit / NGO",
  "Government / Public Sector",
  "Other",
] as const;
