import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "surface-bright": "#31394d",
        "surface-dim": "#0b1326",
        "surface-variant": "#2d3449",
        "surface": "#0b1326",
        "background": "#0b1326",
        "outline": "#849396",
        "outline-variant": "#3b494c",
        "primary": "#c3f5ff",
        "primary-container": "#00e5ff",
        "primary-fixed": "#9cf0ff",
        "primary-fixed-dim": "#00daf3",
        "on-primary": "#00363d",
        "on-primary-container": "#00626e",
        "on-primary-fixed": "#001f24",
        "on-primary-fixed-variant": "#004f58",
        "inverse-primary": "#006875",
        "surface-tint": "#00daf3",
        "secondary": "#b0c6ff",
        "secondary-container": "#0068ed",
        "secondary-fixed": "#d9e2ff",
        "secondary-fixed-dim": "#b0c6ff",
        "on-secondary": "#002d6e",
        "on-secondary-container": "#f2f3ff",
        "on-secondary-fixed": "#001945",
        "on-secondary-fixed-variant": "#00429b",
        "tertiary": "#f1e9ff",
        "tertiary-container": "#d6c9ff",
        "tertiary-fixed": "#e8deff",
        "tertiary-fixed-dim": "#cdbdff",
        "on-tertiary": "#370096",
        "on-tertiary-container": "#622be5",
        "on-tertiary-fixed": "#20005f",
        "on-tertiary-fixed-variant": "#4f00d0",
        "on-surface": "#dae2fd",
        "on-surface-variant": "#bac9cc",
        "on-background": "#dae2fd",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        "3xl": "64px",
        gutter: "24px",
        unit: "4px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "500" }],
      },
      keyframes: {
        "status-pulse": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.4" },
        },
      },
      animation: {
        "status-pulse": "status-pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [],
};
export default config;
