import { demoReports, demoKpis } from "@/lib/demo-data";

export default function ReportsPage() {
  return (
    <div className="space-y-lg py-lg">
      <div className="flex justify-between items-end">
        <div>
          <h1 className="text-headline-lg font-bold text-on-surface tracking-tight mb-xs">Reports & Analytics</h1>
          <p className="text-body-md text-on-surface-variant">Performance insights generated by your Reporting Agent.</p>
        </div>
        <button className="flex items-center gap-xs px-lg py-sm bg-primary-container text-on-primary-container font-mono text-label-md font-bold rounded-xl hover:brightness-105 transition-all active:scale-95">
          <span className="material-symbols-outlined text-body-sm">add</span>
          Generate Report
        </button>
      </div>

      {/* KPI overview */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-md">
        {[
          { label: "Lead Accuracy", value: `${demoKpis.leadAccuracy}%`, icon: "target" },
          { label: "Email Deliverability", value: `${demoKpis.emailDeliverability}%`, icon: "mark_email_read" },
          { label: "Reply Rate", value: `${demoKpis.replyRate}%`, icon: "reply" },
          { label: "Meeting Rate", value: `${demoKpis.meetingRate}%`, icon: "event" },
        ].map(({ label, value, icon }) => (
          <div key={label} className="bg-surface-container-low border border-outline-variant rounded-xl p-lg ai-glow">
            <div className="flex justify-between items-start mb-md">
              <span className="font-mono text-label-sm text-on-surface-variant uppercase tracking-widest">{label}</span>
              <span
                className="material-symbols-outlined text-primary text-body-sm"
                style={{ fontVariationSettings: "'FILL' 1" }}
              >
                {icon}
              </span>
            </div>
            <div className="text-display-lg font-bold text-on-surface">{value}</div>
          </div>
        ))}
      </div>

      {/* Report list */}
      <div className="bg-surface-container-low border border-outline-variant rounded-xl overflow-hidden">
        <div className="p-lg border-b border-outline-variant bg-surface-container-lowest">
          <h2 className="text-headline-sm font-bold text-on-surface">Generated Reports</h2>
        </div>
        <div className="divide-y divide-outline-variant">
          {demoReports.map((r) => (
            <div
              key={r.id}
              className="p-lg flex items-center justify-between hover:bg-surface-container-high transition-colors cursor-pointer"
            >
              <div className="flex items-center gap-md">
                <div className="w-10 h-10 bg-surface-container-high border border-outline-variant rounded-xl flex items-center justify-center">
                  <span
                    className="material-symbols-outlined text-primary text-body-sm"
                    style={{ fontVariationSettings: "'FILL' 1" }}
                  >
                    description
                  </span>
                </div>
                <div>
                  <div className="text-body-sm font-medium text-on-surface">{r.name}</div>
                  <div className="font-mono text-label-sm text-on-surface-variant">
                    {r.date} · {r.type}
                  </div>
                </div>
              </div>
              <div className="flex items-center gap-lg">
                <div className="text-right">
                  <div className="font-mono text-label-md font-bold text-on-surface">{r.leads.toLocaleString()}</div>
                  <div className="font-mono text-label-sm text-on-surface-variant">leads</div>
                </div>
                <div className="text-right">
                  <div className="font-mono text-label-md font-bold text-primary">{r.meetings}</div>
                  <div className="font-mono text-label-sm text-on-surface-variant">meetings</div>
                </div>
                <button className="text-on-surface-variant hover:text-primary transition-colors">
                  <span className="material-symbols-outlined text-body-sm">download</span>
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
