const notifications = [
  { id: "1", icon: "verified", color: "text-primary", title: "23 new leads qualified", body: "Research Agent completed scan of Nairobi FinTech sector.", time: "2 min ago" },
  { id: "2", icon: "mark_email_read", color: "text-secondary", title: "Email batch verified", body: "1,204 addresses validated — 98.7% deliverability.", time: "18 min ago" },
  { id: "3", icon: "how_to_reg", color: "text-tertiary", title: "Human approval required", body: 'Campaign "Pan-Africa Healthcare" ready to launch — awaiting your review.', time: "1 hr ago" },
  { id: "4", icon: "rocket_launch", color: "text-primary", title: "Campaign launched", body: '"East Africa SaaS CEOs" campaign is now live with 89 leads in pipeline.', time: "3 hr ago" },
  { id: "5", icon: "assessment", color: "text-on-surface-variant", title: "Weekly report ready", body: "Your weekly performance report has been generated by the Reporting Agent.", time: "Yesterday" },
];

export default function NotificationsPage() {
  return (
    <div className="space-y-lg py-lg max-w-2xl">
      <div className="flex justify-between items-end">
        <div>
          <h1 className="text-headline-lg font-bold text-on-surface tracking-tight mb-xs">Notifications</h1>
          <p className="text-body-md text-on-surface-variant">Agent activity and system alerts.</p>
        </div>
        <button className="font-mono text-label-sm text-primary hover:underline">Mark all read</button>
      </div>

      <div className="bg-surface-container-low border border-outline-variant rounded-xl overflow-hidden">
        <div className="divide-y divide-outline-variant">
          {notifications.map((n, i) => (
            <div
              key={n.id}
              className={`flex items-start gap-md p-lg hover:bg-surface-container-high transition-colors cursor-pointer ${i < 3 ? "border-l-2 border-primary" : ""}`}
            >
              <div className="w-10 h-10 bg-surface-container-high border border-outline-variant rounded-xl flex items-center justify-center shrink-0">
                <span
                  className={`material-symbols-outlined text-body-sm ${n.color}`}
                  style={{ fontVariationSettings: "'FILL' 1" }}
                >
                  {n.icon}
                </span>
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex justify-between items-start gap-md">
                  <p className="text-body-sm font-semibold text-on-surface">{n.title}</p>
                  <span className="font-mono text-label-sm text-on-surface-variant shrink-0">{n.time}</span>
                </div>
                <p className="text-body-sm text-on-surface-variant mt-xs">{n.body}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
